-- BetLab PostgreSQL/Supabase schema.
-- Apply in a dedicated project before replacing the local SQLite adapter.
create table if not exists public.strategies (
  id text primary key,
  name text not null,
  family text not null,
  stage text not null,
  priority text not null,
  requires_intraday boolean not null default false,
  description text not null,
  created_at timestamptz not null default now()
);
create table if not exists public.odds_snapshots (
  id bigint generated by default as identity primary key,
  event_id text not null,
  sport text not null,
  competition text,
  bookmaker text not null,
  market text not null,
  selection text not null,
  line numeric,
  odds numeric not null check (odds > 1),
  observed_at timestamptz not null,
  source text,
  created_at timestamptz not null default now()
);
create index if not exists idx_snap_event_time on public.odds_snapshots(event_id, observed_at);
create index if not exists idx_snap_market on public.odds_snapshots(sport, market, observed_at);
create table if not exists public.signals (
  id bigint generated by default as identity primary key,
  event_id text not null,
  strategy_id text not null references public.strategies(id),
  market text not null,
  selection text not null,
  bookmaker text,
  odds numeric not null,
  p_market numeric,
  p_model numeric,
  p_shrunk numeric,
  ev_raw numeric,
  ev_robust numeric,
  decision text not null check (decision in ('NO_BET','SHADOW_BET','CANARY','PRODUCTION')),
  revision_of bigint references public.signals(id),
  created_at timestamptz not null,
  result text,
  profit numeric,
  closing_odds numeric
);
create index if not exists idx_signal_created on public.signals(created_at desc);
create table if not exists public.research_trials (
  id bigint generated by default as identity primary key,
  strategy_id text not null references public.strategies(id),
  version text not null,
  parameters_json jsonb not null,
  train_period text,
  validation_period text,
  test_period text,
  roi numeric,
  sharpe numeric,
  brier numeric,
  clv numeric,
  selected boolean not null default false,
  rejected_reason text,
  created_at timestamptz not null default now()
);
create table if not exists public.regulatory_rules (
  id bigint generated by default as identity primary key,
  jurisdiction text not null,
  version_date date not null,
  sport text,
  competition text,
  phase text,
  market text,
  allowed boolean not null,
  source_url text,
  created_at timestamptz not null default now()
);
-- Security note: keep service-role credentials server-side only. Add RLS policies before exposing direct browser access.
