insert into public.strategies (id,name,family,stage,priority,requires_intraday,description) values
  ('market_consensus','Market Consensus','MARKET','BENCHMARK','P0',false,'Médiane des probabilités de-viggées multi-books.'),
  ('weighted_consensus','Weighted Consensus','MARKET','LAB','P1',false,'Pondère les books selon calibration, log-loss et fraîcheur appris sur TRAIN.'),
  ('sharp_soft','Sharp vs Soft','MARKET_LAG','LAB','P1',true,'Compare une référence apprise au bookmaker cible sans supposer Pinnacle oracle.'),
  ('opening_closing','Opening → Closing Move','MARKET_MOVE','LAB','P1',false,'Mesure l’information contenue dans le mouvement ouverture-clôture.'),
  ('bookmaker_lag','Leader-Follower Lag','MARKET_LAG','LAB','P1',true,'Apprend qui mène chaque marché et mesure le délai des followers.'),
  ('market_dispersion','Market Dispersion','MARKET','LAB','P1',true,'MAD inter-books et isolement robuste d’un bookmaker.'),
  ('book_fingerprint','Bookmaker Fingerprinting','MARKET','LAB','P1',true,'Calibration, marge, rapidité et biais par sport/marché/book.'),
  ('favorite_longshot','Favorite–Longshot Bias','BEHAVIOR','LAB','P1',false,'Calibration et ROI par tranche de cote, sport et marché.'),
  ('result_illusion','Result Illusion Index','REGRESSION','LAB','P1',false,'Résultats récents vs performances sous-jacentes.'),
  ('xg_regression','xG Regression','REGRESSION','LAB','P1',false,'Recherche les écarts buts/xG susceptibles de régresser.'),
  ('ah_oracle','Asian Handicap Oracle','CROSS_MARKET','LAB','P1',false,'Utilise AH comme estimation de force pour dériver d’autres marchés.'),
  ('ah_1x2_gap','AH–1X2 Gap','CROSS_MARKET','LAB','P1',false,'Détecte une incohérence entre force AH et prix 1X2.'),
  ('market_fundamental','Market + Fundamentals','META','LAB','P1',false,'Modèle résiduel qui cherche l’information absente du marché.'),
  ('surface_elo','Surface Elo','TENNIS','LAB','P1',false,'Elo spécifique à la surface, benchmark indépendant.'),
  ('market_surface_elo','Market + Surface Elo','TENNIS','LAB','P1',false,'Résiduel Surface Elo vs probabilité de marché.'),
  ('information_half_life','Information Half-Life','MARKET_LAG','LAB','P1',true,'Mesure t50/t80/t95 de l’intégration d’une information.'),
  ('consensus_catchup','Consensus Catch-Up','MARKET_LAG','LAB','P1',true,'Plusieurs books convergent pendant qu’un book reste stale.'),
  ('role_shock','Role Shock','PLAYER_PROP','LAB','P1',true,'Changement de rôle qui rend la moyenne saison partiellement obsolète.'),
  ('minutes_shock','Minutes Shock','PLAYER_PROP','LAB','P1',true,'Projection volume = minutes attendues × taux conditionnel.'),
  ('usage_redistribution','Usage Redistribution','PLAYER_PROP','LAB','P1',true,'Redistribution structurée après absence d’un joueur.'),
  ('false_value','False Value Detector','RISK_FILTER','LAB','P1',false,'Pénalise incertitude, grosses cotes et désaccord modèles.'),
  ('agreement_edge','Agreement-Adjusted Edge','RISK_FILTER','LAB','P1',false,'Réduit l’EV quand un modèle est isolé.'),
  ('error_regime','Error Regime Detector','META','LAB','P1',true,'Cartographie les contextes où le marché se trompe davantage.'),
  ('pressure_accel','Pressure Acceleration','LIVE','LAB','P2',true,'Accélération de pression live comparée à la réaction du prix.'),
  ('goal_surprise','Goal Surprise Engine','LIVE','LAB','P2',true,'Mesure la réaction du marché selon la surprise d’un but.'),
  ('boost_truth','Boost Truth Engine','PROMO','LAB','P2',true,'Compare cote boostée au consensus fair et au modèle shrunk.')
on conflict (id) do update set name=excluded.name, family=excluded.family, stage=excluded.stage, priority=excluded.priority, requires_intraday=excluded.requires_intraday, description=excluded.description;
