import { robustEV } from './math.mjs';

const SUPABASE_URL = (process.env.SUPABASE_URL || '').replace(/\/$/, '');
const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY || '';
const REMOTE = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);

let localDb = null;
async function local() {
  if (!localDb) localDb = await import('./db.mjs');
  return localDb;
}

async function rpc(name, args = {}) {
  if (!REMOTE) throw new Error('Supabase remote store is not configured');
  const response = await fetch(`${SUPABASE_URL}/rest/v1/rpc/${name}`, {
    method: 'POST',
    headers: {
      apikey: SUPABASE_PUBLISHABLE_KEY,
      'content-type': 'application/json',
      accept: 'application/json'
    },
    body: JSON.stringify(args)
  });
  const raw = await response.text();
  let body = null;
  try { body = raw ? JSON.parse(raw) : null; } catch { body = raw; }
  if (!response.ok) {
    const message = body?.message || body?.hint || body?.details || String(body || response.statusText);
    throw new Error(`Supabase RPC ${name}: ${message}`);
  }
  return body;
}

export function storeMode() { return REMOTE ? 'SUPABASE_READ_ONLY' : 'SQLITE_LOCAL'; }

export async function dashboardStats() {
  if (REMOTE) return rpc('betlab_public_dashboard');
  const { get } = await local();
  const strategies = get('SELECT COUNT(*) AS n FROM strategies').n;
  const intraday = get('SELECT COUNT(*) AS n FROM strategies WHERE requires_intraday=1').n;
  const snapshots = get('SELECT COUNT(*) AS n FROM odds_snapshots').n;
  const signals = get('SELECT COUNT(*) AS n FROM signals').n;
  const shadow = get("SELECT COUNT(*) AS n FROM signals WHERE decision='SHADOW_BET'").n;
  return { strategies, intraday, snapshots, signals, shadow, regulatoryMode: 'DEFAULT_DENY_UNTIL_RULES_LOADED' };
}

export async function listStrategies() {
  if (REMOTE) return (await rpc('betlab_public_strategies')) || [];
  const { all } = await local();
  return all('SELECT * FROM strategies ORDER BY priority, family, name');
}

export async function listSnapshots(limit = 100) {
  if (REMOTE) return (await rpc('betlab_public_snapshots', { p_limit: limit })) || [];
  const { all } = await local();
  return all('SELECT * FROM odds_snapshots ORDER BY observed_at DESC, id DESC LIMIT ?', limit);
}

export async function insertSnapshots(items) {
  if (REMOTE) throw new Error('Remote Supabase writes are disabled in the public adapter. Use the private Supabase collectors or run SQLite local mode.');
  const { run } = await local();
  let inserted = 0;
  for (const x of items) {
    const r = run(`INSERT OR IGNORE INTO odds_snapshots(event_id,sport,competition,bookmaker,market,selection,line,odds,observed_at,source)
      VALUES (?,?,?,?,?,?,?,?,?,?)`, x.event_id, x.sport, x.competition || null, x.bookmaker, x.market, x.selection,
      x.line ?? null, Number(x.odds), x.observed_at, x.source || null);
    inserted += Number(r.changes || 0);
  }
  return inserted;
}

export async function listSignals(limit = 100) {
  if (REMOTE) return (await rpc('betlab_public_signals', { p_limit: limit })) || [];
  const { all } = await local();
  return all(`SELECT s.*, st.name AS strategy_name FROM signals s LEFT JOIN strategies st ON st.id=s.strategy_id ORDER BY s.created_at DESC, s.id DESC LIMIT ?`, limit);
}

export async function insertSignal(x) {
  let calc = {};
  if ([x.p_model, x.p_market, x.odds].every((v) => Number.isFinite(Number(v)))) {
    calc = robustEV({
      modelP: Number(x.p_model),
      marketP: Number(x.p_market),
      odds: Number(x.odds),
      reliability: Number(x.reliability ?? .25),
      uncertainty: Number(x.uncertainty ?? .03)
    });
  }
  const created = x.created_at || new Date().toISOString();

  if (REMOTE) throw new Error('Remote Supabase writes are disabled in the public adapter. SHADOW signals are generated by the private Supabase engine.');

  const { run } = await local();
  const r = run(`INSERT INTO signals(event_id,strategy_id,market,selection,bookmaker,odds,p_market,p_model,p_shrunk,ev_raw,ev_robust,decision,revision_of,created_at)
    VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`, x.event_id, x.strategy_id, x.market, x.selection, x.bookmaker || null, Number(x.odds),
    x.p_market ?? null, x.p_model ?? null, calc.pShrunk ?? x.p_shrunk ?? null, calc.evRaw ?? x.ev_raw ?? null,
    calc.evRobust ?? x.ev_robust ?? null, x.decision, x.revision_of ?? null, created);
  return { id: Number(r.lastInsertRowid), created_at: created, ...calc };
}

export async function regulatoryStatus() {
  if (REMOTE) return rpc('betlab_public_regulatory_status');
  const { get } = await local();
  const last = get('SELECT MAX(version_date) AS version_date, COUNT(*) AS n FROM regulatory_rules');
  return {
    jurisdiction: 'FR',
    loaded: Number(last?.n || 0) > 0,
    versionDate: last?.version_date || null,
    policy: 'DEFAULT_DENY_WITHOUT_CURRENT_RULE'
  };
}
