export const STRATEGIES = [
  ['market_consensus','Market Consensus','MARKET','BENCHMARK','P0',0,'Médiane des probabilités de-viggées multi-books.'],
  ['weighted_consensus','Weighted Consensus','MARKET','LAB','P1',0,'Pondère les books selon calibration, log-loss et fraîcheur appris sur TRAIN.'],
  ['sharp_soft','Sharp vs Soft','MARKET_LAG','LAB','P1',1,'Compare une référence apprise au bookmaker cible sans supposer Pinnacle oracle.'],
  ['opening_closing','Opening → Closing Move','MARKET_MOVE','LAB','P1',0,'Mesure l’information contenue dans le mouvement ouverture-clôture.'],
  ['bookmaker_lag','Leader-Follower Lag','MARKET_LAG','LAB','P1',1,'Apprend qui mène chaque marché et mesure le délai des followers.'],
  ['market_dispersion','Market Dispersion','MARKET','LAB','P1',1,'MAD inter-books et isolement robuste d’un bookmaker.'],
  ['book_fingerprint','Bookmaker Fingerprinting','MARKET','LAB','P1',1,'Calibration, marge, rapidité et biais par sport/marché/book.'],
  ['favorite_longshot','Favorite–Longshot Bias','BEHAVIOR','LAB','P1',0,'Calibration et ROI par tranche de cote, sport et marché.'],
  ['result_illusion','Result Illusion Index','REGRESSION','LAB','P1',0,'Résultats récents vs performances sous-jacentes.'],
  ['xg_regression','xG Regression','REGRESSION','LAB','P1',0,'Recherche les écarts buts/xG susceptibles de régresser.'],
  ['ah_oracle','Asian Handicap Oracle','CROSS_MARKET','LAB','P1',0,'Utilise AH comme estimation de force pour dériver d’autres marchés.'],
  ['ah_1x2_gap','AH–1X2 Gap','CROSS_MARKET','LAB','P1',0,'Détecte une incohérence entre force AH et prix 1X2.'],
  ['market_fundamental','Market + Fundamentals','META','LAB','P1',0,'Modèle résiduel qui cherche l’information absente du marché.'],
  ['surface_elo','Surface Elo','TENNIS','LAB','P1',0,'Elo spécifique à la surface, benchmark indépendant.'],
  ['market_surface_elo','Market + Surface Elo','TENNIS','LAB','P1',0,'Résiduel Surface Elo vs probabilité de marché.'],
  ['information_half_life','Information Half-Life','MARKET_LAG','LAB','P1',1,'Mesure t50/t80/t95 de l’intégration d’une information.'],
  ['consensus_catchup','Consensus Catch-Up','MARKET_LAG','LAB','P1',1,'Plusieurs books convergent pendant qu’un book reste stale.'],
  ['role_shock','Role Shock','PLAYER_PROP','LAB','P1',1,'Changement de rôle qui rend la moyenne saison partiellement obsolète.'],
  ['minutes_shock','Minutes Shock','PLAYER_PROP','LAB','P1',1,'Projection volume = minutes attendues × taux conditionnel.'],
  ['usage_redistribution','Usage Redistribution','PLAYER_PROP','LAB','P1',1,'Redistribution structurée après absence d’un joueur.'],
  ['false_value','False Value Detector','RISK_FILTER','LAB','P1',0,'Pénalise incertitude, grosses cotes et désaccord modèles.'],
  ['agreement_edge','Agreement-Adjusted Edge','RISK_FILTER','LAB','P1',0,'Réduit l’EV quand un modèle est isolé.'],
  ['error_regime','Error Regime Detector','META','LAB','P1',1,'Cartographie les contextes où le marché se trompe davantage.'],
  ['pressure_accel','Pressure Acceleration','LIVE','LAB','P2',1,'Accélération de pression live comparée à la réaction du prix.'],
  ['goal_surprise','Goal Surprise Engine','LIVE','LAB','P2',1,'Mesure la réaction du marché selon la surprise d’un but.'],
  ['boost_truth','Boost Truth Engine','PROMO','LAB','P2',1,'Compare cote boostée au consensus fair et au modèle shrunk.']
].map(([id,name,family,stage,priority,requiresIntraday,description]) => ({id,name,family,stage,priority,requiresIntraday:Boolean(requiresIntraday),description}));
