import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "jsr:@supabase/supabase-js@2";
const SOURCE_URL="https://www.football-data.co.uk/fixtures.csv";
const SOURCE="football-data-fixtures";
const COMP:Record<string,string>={E0:"Premier League",E1:"Championship",F1:"Ligue 1",F2:"Ligue 2",D1:"Bundesliga",D2:"Bundesliga 2",I1:"Serie A",I2:"Serie B",SP1:"LaLiga Santander",SP2:"Liga 2",P1:"Liga NOS",N1:"Eredivisie",B1:"Jupiler Pro League",SC0:"Cinch Premiership",T1:"Spor Toto Süper Lig",G1:"Super League Greece"};
function parseCSV(t:string){const rs:string[][]=[];let r:string[]=[],f="",q=false;for(let i=0;i<t.length;i++){const c=t[i];if(q){if(c==='"'&&t[i+1]==='"'){f+='"';i++;}else if(c==='"')q=false;else f+=c;}else{if(c==='"')q=true;else if(c===','){r.push(f);f="";}else if(c==='\n'){r.push(f.replace(/\r$/,''));f="";if(r.some(x=>x!==''))rs.push(r);r=[];}else f+=c;}}r.push(f.replace(/\r$/,''));if(r.some(x=>x!==''))rs.push(r);if(!rs.length)return[] as Record<string,string>[];const h=rs[0].map(x=>x.trim().replace(/^\uFEFF/,''));return rs.slice(1).map(v=>Object.fromEntries(h.map((k,i)=>[k,v[i]??''])));}const cl=(s:any)=>String(s||'').trim().replace(/\s+/g,' ');const sl=(s:string)=>cl(s).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');function num(r:any,ks:string[]){for(const k of ks){const v=Number(r[k]);if(Number.isFinite(v)&&v>1)return v;}return null;}function line(r:any,ks:string[]){for(const k of ks){const v=Number(r[k]);if(Number.isFinite(v))return v;}return null;}
Deno.serve(async(req:Request)=>{try{
 const sb=createClient(Deno.env.get('SUPABASE_URL')!,Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,{auth:{persistSession:false}});
 const {data:ctx,error:ctxError}=await sb.rpc('betlab_service_refresh_context',{p_source:SOURCE});if(ctxError)throw ctxError;
 const provided=req.headers.get('x-betlab-cron-key')||'';if(!provided||!ctx?.key||provided!==ctx.key)return Response.json({ok:false,error:'Unauthorized'},{status:401});
 if(ctx?.lastFetchedAt){const age=(Date.now()-new Date(ctx.lastFetchedAt).getTime())/60000;if(age<30)return Response.json({ok:true,skipped:true,reason:'RECENT_RUN',ageMinutes:Math.round(age*10)/10});}
 const resp=await fetch(SOURCE_URL,{headers:{'user-agent':'BetLabResearch/1.0','accept':'text/csv,*/*'},cache:'no-store'});if(!resp.ok)throw new Error(`Football-Data HTTP ${resp.status}`);const text=await resp.text();if(/^\s*</.test(text))throw new Error('Football-Data returned HTML instead of CSV');
 const rows=parseCSV(text),at=new Date().toISOString(),items:any[]=[];const divs=new Set<string>();let accepted=0,latest='';
 for(const row of rows){const div=cl(row.Div);if(!COMP[div])continue;const home=cl(row.HomeTeam),away=cl(row.AwayTeam);if(!home||!away)continue;accepted++;divs.add(div);if(cl(row.Date)>latest)latest=cl(row.Date);const event_id=`fd:${div}:${cl(row.Date)}:${sl(home)}:${sl(away)}`,base={event_id,sport:'football',competition:div,observed_at:at};
  for(const [book,os] of [['market_avg',[num(row,['AvgH']),num(row,['AvgD']),num(row,['AvgA'])]],['market_max',[num(row,['MaxH']),num(row,['MaxD']),num(row,['MaxA'])]],['bet365',[num(row,['B365H']),num(row,['B365D']),num(row,['B365A'])]]] as any){if(os.every((x:any)=>x!==null))['HOME','DRAW','AWAY'].forEach((s,i)=>items.push({...base,bookmaker:book,market:'H2H',selection:s,odds:os[i]}));}
  for(const [book,o,u] of [['market_avg',num(row,['Avg>2.5','AvgO2.5']),num(row,['Avg<2.5','AvgU2.5'])],['market_max',num(row,['Max>2.5','MaxO2.5']),num(row,['Max<2.5','MaxU2.5'])],['bet365',num(row,['B365>2.5','B365O2.5']),num(row,['B365<2.5','B365U2.5'])]] as any){if(o&&u){items.push({...base,bookmaker:book,market:'TOTAL_2_5',selection:'OVER',line:2.5,odds:o});items.push({...base,bookmaker:book,market:'TOTAL_2_5',selection:'UNDER',line:2.5,odds:u});}}
  const ah=line(row,['AHh','Handicap']);if(ah!==null)for(const [book,h,a] of [['market_avg',num(row,['AvgAHH']),num(row,['AvgAHA'])],['market_max',num(row,['MaxAHH']),num(row,['MaxAHA'])],['bet365',num(row,['B365AHH']),num(row,['B365AHA'])]] as any){if(h&&a){items.push({...base,bookmaker:book,market:'ASIAN_HANDICAP',selection:'HOME',line:ah,odds:h});items.push({...base,bookmaker:book,market:'ASIAN_HANDICAP',selection:'AWAY',line:-ah,odds:a});}}
 }
 const details={sourceUrl:SOURCE_URL,lastModified:resp.headers.get('last-modified'),rowsAccepted:accepted,divisions:[...divs].sort(),latestFixtureDate:latest,warning:'Pinnacle excluded as oracle after Football-Data reliability warning dated 2025-07-23'};
 const {data,error}=await sb.rpc('betlab_service_ingest_feed',{p_source:SOURCE,p_fetched_at:at,p_rows_seen:rows.length,p_details:details,p_items:items});if(error)throw error;
 return Response.json({ok:true,rowsSeen:rows.length,rowsAccepted:accepted,snapshotsPrepared:items.length,ingest:data,details});
}catch(e:any){console.error(e);const msg=e?.message||e?.details||e?.hint||JSON.stringify(e);return Response.json({ok:false,error:msg},{status:500});}});